---
- debug:
    msg: "{{inventory_hostname}}"

- name: Create a realserver
  a10_server_v20:
    host: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    state: "{{state}}"
    validate_certs: no
    partition: "{{partition}}"
    server_name: "{{rserver_name}}"
    server_ip: "{{rserver_ip}}"
    server_status: "{{server_status}}"
    health_monitor: "{{rserver_hm}}"
    slow_start: "{{slow_start}}"
    server_ports:
        - port_num: "{{rserver_port}}"
          protocol: "{{rserver_port_protocol}}"
          health_monitor: "{{rserver_port_hm}}"
          status: "{{rserver_port_status}}"
          state: "{{rserver_port_state}}"
