---
- name: Create NAT pool
  a10_nat_pool_v2:
    validate_certs: no
    host: "{{inventory_hostname}}"
    username: "{{username}}"
    password: "{{password}}"
    name: "{{natpool_name}}"
    start_ip_addr: "{{start_ip_addr}}"
    end_ip_addr: "{{end_ip_addr}}"
    netmask: "{{netmask}}"
    ha_group_id: "{{ha_group_id}}"
    #vrid: "{{vrid}}"
